config/routes.rb
Freewar3::Application.routes.draw do 
  devise_for :members,
             controllers: {
               sessions: "sessions"
             }
  # :param => /.*/ prevents failing on a name with a period
  root :to => 'home#index'
  
  # ukimgs      
  get 'ukimgs/tag/:id/:tag_id/(up|down|report)',
        :as => 'ukimgs_tag',
        :to => 'ukimgs#tag'
      
  get 'ukimgs(/sets/:sets)(/tags/:tags)',
        :as => 'ukimgs',
        :to => 'ukimgs#index'
  
  # about
  scope :controller => :home, :path => '/' do
    get '/about', :action => :about, :as => 'about'
    get '/contact', :action => :contact, :as => 'contact'
    get '/dumps(/:path)', :action => :dumps, :as => 'dumps'
    get '/impressum', :action => :impressum, :as => 'impressum'
  end
  
  # single achievement
  get 'achievement/:name(/:stage)', 
        :as => 'achievement',
        :to => 'achievements#show'
  # Achievements
  scope :as => 'achievements', :controller => :achievements, :path => '/achievements' do
    get '/group_progress/:group/:users.:format',
          :action => 'group_progress',
          :as     => 'group_progress'
          
    get '/rank(/show/:ids)(/page/:page)(/order/:order/:by)(/:world)',
          :action => 'rank',
          :as     => 'rank'
    get '/unachieved(/:world)', 
          :action => 'unachieved',
          :as     => 'unachieved'
    
    get '(/:world)', 
        :action => 'index',
        :as     => 'index'
    root action: 'index'
  end
  
  # Areas  
  scope :as => 'areas', :controller => 'areas', :path => '/areas' do
    get '/:name/places', 
          :action => 'places',
          :as => 'places'
    get '/:name', 
          :action => 'show',
          :as => 'show'
  end
  
  
  # single clan
  get 'clan/:id/:world', 
        :as => 'clan', 
        :to => 'clans#show'
  # clans
  scope :as => 'clans', :controller => 'clans', :path => '/clans' do
    match '/:action(/page/:page)(/order/:order/:by)(/:world)(/from/:starttime/till/:endtime)(/like/*name)', 
          :defaults => {
            :page   => 1
          },
          :via => [:get, :post]
    root action: 'index'
  end
  
  # single extension
  get '/extensions/show/:id', :to => 'extensions#show', :as => 'extension'
  
  # extensions
  scope :as => 'extensions', :controller => :extensions, :path => '/extensions' do 
    get '/:action'
    
    root :action => :index
  end
  
      
  # graphs
  scope :as => 'graphs', :controller => :graphs, :path => '/graphs' do
    root :action => 'index'
    
    match '/achievements(/:mode)', 
          :action => 'achievements', 
          :as => 'achievements',
          :via => [:get, :post] 
    match '/statistics',
          action: 'statistics',
          as: 'statistics',
          via: [:get, :post]
  end
  
  # map
  scope :as => 'map', :controller => :map, :path => '/map' do
    post '',
         :action => 'index'
    get '(/:x,:y)(/radius/:radius)',
        :action => 'index',
        :as => 'root'

    get '/show/:x,:y',
        :action => 'show',
        :as => 'place'
  end
  
  #news
  get '/news' => 'feeds#news', :as => 'news_feed',
      :defaults => {
        :format => 'atom'
      }
  get '/news/:id', :to => 'home#show', :as => 'news'
  
  # npcs
  get '/npcs/api(.:format)', :to => 'npcs#api', :as => 'npcs_api'
  resources :npcs, only: [:index, :show]
  
  get '/spotlights', as: "spotlights", to: "spotlights#show"
  
  # slmania
  scope as: 'slmania', controller: :slmania, path: '/slmania' do
    root action: 'index', as: 'index'
    
    scope path: '/:member', as: 'user' do 
      get '/npc/:name',  action: 'evaluate_npc', as: 'npc'
      get '/item/:name', action: 'evaluate_item', as: 'item'
      get '/soul_capsule', action: 'soul_capsule', as: 'soul_capsule'
      
      root action: 'list_actions'
    end
  end
  
  # single statistic/
  get 'statistic/:name(/:world)', 
        :as => 'statistic',
        :to => 'statistics#show'
  
  # statistics
  scope :as => 'statistics', :controller => :statistics, :path => '/statistics' do
    root action: 'index'
    
    get '/:action(/:world)'
  end
  
  # tools
  scope :as => 'tools', :controller => 'tools', :path => 'tools' do
    match '/railpatterns(/:active_pattern)', :as => 'railpatterns', 
                                          :action => 'railpatterns',
                                          :defaults => {
                                            :active_pattern => "Lebensschnitt"
                                          },
                                          :via => [:get, :post]
    match '/ability_calc', :as => 'ability_calc', :action => 'ability_calc', :via => [:get, :post]
  end
  
  # single user
  get 'user/:name/:world', 
        :as => 'user', 
        :name => /.*/, 
        :to => 'users#show'
  # users
  scope :as => 'users', :controller => 'users', :path => 'users' do
    match '/:action(/page/:page)(/order/:order/:by)(/:world)(/race/:race)(/from/:starttime/till/:endtime)(/like/*name)', 
          :defaults => {
            :page   => 1
          },
          :via => [:get, :post]
    root action: 'index'
  end
 
  # adminpanel
  namespace :admin do 
    resources :achievements, :dumps, :members, :npcs, :news, :races, :worlds
    root :to => 'base#index'
  end
  
  match "*path", :to => "application#routing_error", :via => :all
end

app/models/dump.rb
class Dump < ActiveRecord::Base
  scope :shared, -> { where(public: true) }
  
  def children
    return system_path.children(false) if subs?
    [nil]
  end
  
  def files
    children.map { |f| web_path(f) }
  end
  
  def updated_at
    return system_path.mtime unless subs?
    children.map { |f| system_path.join(f) }.map(&:mtime).max
  end
  
  def path
    Pathname.new(super)
  end
  
  def subs?
    system_path.directory?
  end
  
  def web_path(file = nil)
    unless file.nil?
      return path.join(file)
    end
    path
  end
  
  private   
  
  def system_path
    Rails.root.join("public", "dumps", path)
  end
end

app/controllers/admin/dumps_controller.rb
class Admin::DumpsController < Admin::BaseController
  before_action :set_admin_dump, only: [:show, :edit, :update, :destroy]

  # GET /admin/dumps
  def index
    @admin_dumps = ::Dump.all
  end

  # GET /admin/dumps/1
  def show
  end

  # GET /admin/dumps/new
  def new
    @admin_dump = ::Dump.new
  end

  # GET /admin/dumps/1/edit
  def edit
  end

  # POST /admin/dumps
  def create
    @admin_dump = ::Dump.new(admin_dump_params)

    if @admin_dump.save
      redirect_to [:admin, @admin_dump], notice: 'Dump was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /admin/dumps/1
  def update
    if @admin_dump.update(admin_dump_params)
      redirect_to [:admin, @admin_dump], notice: 'Dump was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /admin/dumps/1
  def destroy
    @admin_dump.destroy
    redirect_to admin_dumps_url, notice: 'Dump was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_dump
      @admin_dump = ::Dump.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def admin_dump_params
      params.require(:dump).permit(:name, :path, :public)
    end
end

app/helpers/dumps_helper.rb
module DumpsHelper
  def dump_path(dump)
    "/dumps/#{dump.web_path}"
  end
end

app/views/admin/dumps/_form.html.erb
<%= form_for([:admin, @admin_dump]) do |f| %>
  <% if @admin_dump.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_dump.errors.count, "error") %> prohibited this admin_dump from being saved:</h2>

      <ul>
      <% @admin_dump.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name, Dump.human_attribute_name(:name) %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :path, Dump.human_attribute_name(:path) %>
    <%= f.text_field :path %>
  </div>

  <div class="field">
    <%= f.label :public, Dump.human_attribute_name(:public) %>
    <%= f.check_box :public %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/dumps/edit.html.erb
<h1>Editing admin_dump</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @admin_dump] %> |
<%= link_to 'Back', admin_dumps_path %>

app/views/admin/dumps/index.html.erb
<h1>Listing admin_dumps</h1>

<table>
  <thead>
    <tr>
      <th><%= Dump.human_attribute_name(:name) %></th>
      <th><%= Dump.human_attribute_name(:path) %></th>
      <th><%= Dump.human_attribute_name(:files) %></th>
      <th><%= Dump.human_attribute_name(:updated_at) %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_dumps.each do |admin_dump| %>
      <tr>
        <td><%= admin_dump.name %></td>
        <td><%= dump_path(admin_dump) %></td>
        <td><%= admin_dump.files %></td>
        <td><%= time_tag admin_dump.updated_at %></td>
        <td><%= link_to 'Show', [:admin, admin_dump] %></td>
        <td><%= link_to 'Edit', edit_admin_dump_path(admin_dump) %></td>
        <td><%= link_to 'Destroy', [:admin, admin_dump], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dump', new_admin_dump_path %>

app/views/admin/dumps/new.html.erb
<h1>New admin_dump</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_dumps_path %>

app/views/admin/dumps/show.html.erb
<%= link_to 'Edit', edit_admin_dump_path(@admin_dump) %> |
<%= link_to 'Back', admin_dumps_path %>