config/routes.rb
Freewar3::Application.routes.draw do 
  devise_for :members,
             controllers: {
               sessions: "sessions"
             }
  # :param => /.*/ prevents failing on a name with a period
  root :to => 'home#index'
  
  # ukimgs      
  get 'ukimgs/tag/:id/:tag_id/(up|down|report)',
        :as => 'ukimgs_tag',
        :to => 'ukimgs#tag'
      
  get 'ukimgs(/sets/:sets)(/tags/:tags)',
        :as => 'ukimgs',
        :to => 'ukimgs#index'
  
  # about
  scope :controller => :home, :path => '/' do
    get '/about', :action => :about, :as => 'about'
    get '/contact', :action => :contact, :as => 'contact'
    get '/dumps(/:path)', :action => :dumps, :as => 'dumps'
    get '/impressum', :action => :impressum, :as => 'impressum'
  end
  
  # single achievement
  get 'achievement/:name(/:stage)', 
        :as => 'achievement',
        :to => 'achievements#show'
  # Achievements
  scope :as => 'achievements', :controller => :achievements, :path => '/achievements' do
    get '/group_progress/:group/:users.:format',
          :action => 'group_progress',
          :as     => 'group_progress'
          
    get '/rank(/show/:ids)(/page/:page)(/order/:order/:by)(/:world)',
          :action => 'rank',
          :as     => 'rank'
    get '/unachieved(/:world)', 
          :action => 'unachieved',
          :as     => 'unachieved'
    
    get '(/:world)', 
        :action => 'index',
        :as     => 'index'
    root action: 'index'
  end
  
  # Areas  
  scope :as => 'areas', :controller => 'areas', :path => '/areas' do
    get '/:name/places', 
          :action => 'places',
          :as => 'places'
    get '/:name', 
          :action => 'show',
          :as => 'show'
  end
  
  
  # single clan
  get 'clan/:id/:world', 
        :as => 'clan', 
        :to => 'clans#show'
  # clans
  scope :as => 'clans', :controller => 'clans', :path => '/clans' do
    match '/:action(/page/:page)(/order/:order/:by)(/:world)(/from/:starttime/till/:endtime)(/like/*name)', 
          :defaults => {
            :page   => 1
          },
          :via => [:get, :post]
    root action: 'index'
  end
  
  # single extension
  get '/extensions/show/:id', :to => 'extensions#show', :as => 'extension'
  
  # extensions
  scope :as => 'extensions', :controller => :extensions, :path => '/extensions' do 
    get '/:action'
    
    root :action => :index
  end
  
      
  # graphs
  scope :as => 'graphs', :controller => :graphs, :path => '/graphs' do
    root :action => 'index'
    
    match '/achievements(/:mode)', 
          :action => 'achievements', 
          :as => 'achievements',
          :via => [:get, :post] 
    match '/statistics',
          action: 'statistics',
          as: 'statistics',
          via: [:get, :post]
  end
  
  # map
  scope :as => 'map', :controller => :map, :path => '/map' do
    post '',
         :action => 'index'
    get '(/:x,:y)(/radius/:radius)',
        :action => 'index',
        :as => 'root'

    get '/show/:x,:y',
        :action => 'show',
        :as => 'place'
  end
  
  #news
  get '/news' => 'feeds#news', :as => 'news_feed',
      :defaults => {
        :format => 'atom'
      }
  get '/news/:id', :to => 'home#show', :as => 'news'
  
  # npcs
  get '/npcs/api(.:format)', :to => 'npcs#api', :as => 'npcs_api'
  resources :npcs, only: [:index, :show]
  
  get '/spotlights', as: "spotlights", to: "spotlights#show"
  
  # slmania
  scope as: 'slmania', controller: :slmania, path: '/slmania' do
    root action: 'index', as: 'index'
    
    scope path: '/:member', as: 'user' do 
      get '/npc/:name',  action: 'evaluate_npc', as: 'npc'
      get '/item/:name', action: 'evaluate_item', as: 'item'
      get '/soul_capsule', action: 'soul_capsule', as: 'soul_capsule'
      
      root action: 'list_actions'
    end
  end
  
  # single statistic/
  get 'statistic/:name(/:world)', 
        :as => 'statistic',
        :to => 'statistics#show'
  
  # statistics
  scope :as => 'statistics', :controller => :statistics, :path => '/statistics' do
    root action: 'index'
    
    get '/:action(/:world)'
  end
  
  # tools
  scope :as => 'tools', :controller => 'tools', :path => 'tools' do
    match '/railpatterns(/:active_pattern)', :as => 'railpatterns', 
                                          :action => 'railpatterns',
                                          :defaults => {
                                            :active_pattern => "Lebensschnitt"
                                          },
                                          :via => [:get, :post]
    match '/ability_calc', :as => 'ability_calc', :action => 'ability_calc', :via => [:get, :post]
  end
  
  # single user
  get 'user/:name/:world', 
        :as => 'user', 
        :name => /.*/, 
        :to => 'users#show'
  # users
  scope :as => 'users', :controller => 'users', :path => 'users' do
    match '/:action(/page/:page)(/order/:order/:by)(/:world)(/race/:race)(/from/:starttime/till/:endtime)(/like/*name)', 
          :defaults => {
            :page   => 1
          },
          :via => [:get, :post]
    root action: 'index'
  end
 
  # adminpanel
  namespace :admin do 
    resources :achievements, :dumps, :members, :npcs, :news, :races, :worlds
    root :to => 'base#index'
  end
  
  match "*path", :to => "application#routing_error", :via => :all
end

app/models/slmania.rb
class Slmania 
  def initialize
    
  end
  
  def blacklist
    @blacklist
  end
  
  def blacklist=(blacklist)
    @blacklist = blacklist
  end
  
  def droplist
    @droplist
  end
  
  def droplist=(droplist)
    @droplist = droplist
  end
  
  def user
    @user
  end
  
  def user=(user)
    @user = user
  end
  
  def evaluate(conditions)
    evaluation = {}
    conditions.each do |key, condition|
      evaluation[key] = {
        # get primaries
        npcs: {
          ids: Npc.where.not(@blacklist || false).where(condition).collect(&:id),
          counts: {}
        },
        drops: ItemsNpc.where(member: @user).includes(:item)
      }
      
      # total action count
      actions = ItemsNpc::defined_enums['action'].keys
      sums = NpcsMember.where(member: @user,
                              npc_id: evaluation[key][:npcs][:ids]).
                        select(actions.map { |action| "SUM(#{action}count) as #{action}count"}).
                        take
      actions.each do |action|
        evaluation[key][:npcs][:counts][action] = sums["#{action}count"]
      end                

      #  drops
      evaluation[key][:drops] = evaluation[key][:drops].where(npc_id: evaluation[key][:npcs][:ids])
      evaluation[key][:drops] = evaluation[key][:drops].where(item_id: @droplist) if @droplist
    end
    
    evaluation
  end
end

app/controllers/slmania_controller.rb
class SlmaniaController < ApplicationController
  def index
    @slmania_users = Member.slmania_public
  end
  
  def list_actions
    @slmania_user = slmania_user
    
    @alphanumerics = Npc.letters
    
    @entities = Npc.slmania_list
  end
  
  def evaluate_npc
    @slmania_user = slmania_user
    
    @slmania = Slmania.new
    @slmania.user = @slmania_user
    
    @evaluations = @slmania.evaluate(Npc::Conditions.npc(params[:name]))
  end
  
  def evaluate_item
    
  end
  
  def soul_capsule
    
  end
  
  protected
  
  def slmania_user
    # own profile
    if member_signed_in? && current_member.try(:id).eql?(params[:id])
      slmania_user = current_member
    else # somebody else
      slmania_user = Member.slmania_public.where(id: params[:id]).take
    end
    
    # no valid user, redirect to index
    if slmania_user.nil?
      redirect_to slmania_index_url
    end
    
    slmania_user
  end
end

app/helpers/slmania_helper.rb
module SlmaniaHelper
end

app/views/slmania/evaluate_item.html.erb
<%#
# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
%>

<%= "evaluate_item.html" %>

app/views/slmania/evaluate_npc.html.erb
<%= debug @evaluations %>
<% @evaluations.each do |group_name, evaluation| %>
  <dl>
    <% evaluation[:npcs][:counts].each do |action, count| %>
      <dt><%= NpcsMember.human_attribute_name("#{action}count") %></dt>
      <dd><%= number_with_delimiter count %></dd>
    <% end %>
  </dl>
  <table class="slmania evaluation" id="<%= group_name.parameterize %>">
  <caption><%= group_name %></caption>
  <thead>
    <tr>
      <th><%= t ".drop.name" %></th>
      <th><%= t ".drop.count" %></th>
      <th><%= t ".drop.action" %></th>
    </tr>
  </thead>
  <tbody>
    <% evaluation[:drops].each do |drop| %>
    <tr>
      <td><%= drop.item.try(:name) || drop.item_id %></td>
      <td><%= drop.count %></td>
      <td><%= drop.action %></td>
    </tr>
    <% end %>
  </tbody>
  </table>
<% end %>

app/views/slmania/index.html.erb
<h1><%= t ".heading" %></h1>

<% if member_signed_in? %>
  <%= link_to ".own_profile", slmania_user_root_url(current_member.id, action: 'list_actions') %>
<% else %>
  <%= t ".no_profile" %>
<% end %>

<h2><%= t ".public_profiles" %></h2>
<ul>
  <% @slmania_users.each do |user| %>
  <li><%= link_to user.name, slmania_user_root_url(user.id, action: 'list_actions') %></li>
  <% end %>
</ul>

app/views/slmania/list_actions.html.erb
<h1><%= t ".heading", name: @slmania_user.name %></h1>
<ul id="slmania_actions" class="nav">
  <li><%= link_to t(".soul_capsule"), slmania_user_soul_capsule_path(@slmania_user.id) %></li>
</ul>

<ol class="nav alphabetic">
  <% @alphanumerics.each do |char| %>
  <li><%= link_to char, "#letter_#{char}" %></li>
  <% end %>
</ol>

<ol class="letters">
  <% letter = nil %>
  <% @entities.each do |entity| %>
    <% if entity.name[0].downcase != letter %>
      <%= "</ol></li>".html_safe unless letter.nil? %>
      <li>
        <a name="letter_<%= entity.name[0].downcase %>"></a>
        <ol class="entities">
    <% end %>
    <li>
      <%= link_to entity.name, slmania_user_path(@slmania_user.id, 
                                                action: "evaluate_#{entity.class.to_s.downcase}", 
                                                name: entity.name) %>
    </li>
    
    <% letter = entity.name[0].downcase %>
  <% end %>
</ol>