config/routes.rb
Freewar3::Application.routes.draw do 
  devise_for :members,
             controllers: {
               sessions: "sessions"
             }
  # :param => /.*/ prevents failing on a name with a period
  root :to => 'home#index'
  
  # ukimgs      
  get 'ukimgs/tag/:id/:tag_id/(up|down|report)',
        :as => 'ukimgs_tag',
        :to => 'ukimgs#tag'
      
  get 'ukimgs(/sets/:sets)(/tags/:tags)',
        :as => 'ukimgs',
        :to => 'ukimgs#index'
  
  # about
  scope :controller => :home, :path => '/' do
    get '/about', :action => :about, :as => 'about'
    get '/contact', :action => :contact, :as => 'contact'
    get '/dumps(/:path)', :action => :dumps, :as => 'dumps'
    get '/impressum', :action => :impressum, :as => 'impressum'
  end
  
  # single achievement
  get 'achievement/:name(/:stage)', 
        :as => 'achievement',
        :to => 'achievements#show'
  # Achievements
  scope :as => 'achievements', :controller => :achievements, :path => '/achievements' do
    get '/group_progress/:group/:users.:format',
          :action => 'group_progress',
          :as     => 'group_progress'
          
    get '/rank(/show/:ids)(/page/:page)(/order/:order/:by)(/:world)',
          :action => 'rank',
          :as     => 'rank'
    get '/unachieved(/:world)', 
          :action => 'unachieved',
          :as     => 'unachieved'
    
    get '(/:world)', 
        :action => 'index',
        :as     => 'index'
    root action: 'index'
  end
  
  # Areas  
  scope :as => 'areas', :controller => 'areas', :path => '/areas' do
    get '/:name/places', 
          :action => 'places',
          :as => 'places'
    get '/:name', 
          :action => 'show',
          :as => 'show'
  end
  
  
  # single clan
  get 'clan/:id/:world', 
        :as => 'clan', 
        :to => 'clans#show'
  # clans
  scope :as => 'clans', :controller => 'clans', :path => '/clans' do
    match '/:action(/page/:page)(/order/:order/:by)(/:world)(/from/:starttime/till/:endtime)(/like/*name)', 
          :defaults => {
            :page   => 1
          },
          :via => [:get, :post]
    root action: 'index'
  end
  
  # single extension
  get '/extensions/show/:id', :to => 'extensions#show', :as => 'extension'
  
  # extensions
  scope :as => 'extensions', :controller => :extensions, :path => '/extensions' do 
    get '/:action'
    
    root :action => :index
  end
  
      
  # graphs
  scope :as => 'graphs', :controller => :graphs, :path => '/graphs' do
    root :action => 'index'
    
    match '/achievements(/:mode)', 
          :action => 'achievements', 
          :as => 'achievements',
          :via => [:get, :post] 
    match '/statistics',
          action: 'statistics',
          as: 'statistics',
          via: [:get, :post]
  end
  
  # map
  scope :as => 'map', :controller => :map, :path => '/map' do
    post '',
         :action => 'index'
    get '(/:x,:y)(/radius/:radius)',
        :action => 'index',
        :as => 'root'

    get '/show/:x,:y',
        :action => 'show',
        :as => 'place'
  end
  
  #news
  get '/news' => 'feeds#news', :as => 'news_feed',
      :defaults => {
        :format => 'atom'
      }
  get '/news/:id', :to => 'home#show', :as => 'news'
  
  # npcs
  get '/npcs/api(.:format)', :to => 'npcs#api', :as => 'npcs_api'
  resources :npcs, only: [:index, :show]
  
  get '/spotlights', as: "spotlights", to: "spotlights#show"
  
  # slmania
  scope as: 'slmania', controller: :slmania, path: '/slmania' do
    root action: 'index', as: 'index'
    
    scope path: '/:member', as: 'user' do 
      get '/npc/:name',  action: 'evaluate_npc', as: 'npc'
      get '/item/:name', action: 'evaluate_item', as: 'item'
      get '/soul_capsule', action: 'soul_capsule', as: 'soul_capsule'
      
      root action: 'list_actions'
    end
  end
  
  # single statistic/
  get 'statistic/:name(/:world)', 
        :as => 'statistic',
        :to => 'statistics#show'
  
  # statistics
  scope :as => 'statistics', :controller => :statistics, :path => '/statistics' do
    root action: 'index'
    
    get '/:action(/:world)'
  end
  
  # tools
  scope :as => 'tools', :controller => 'tools', :path => 'tools' do
    match '/railpatterns(/:active_pattern)', :as => 'railpatterns', 
                                          :action => 'railpatterns',
                                          :defaults => {
                                            :active_pattern => "Lebensschnitt"
                                          },
                                          :via => [:get, :post]
    match '/ability_calc', :as => 'ability_calc', :action => 'ability_calc', :via => [:get, :post]
  end
  
  # single user
  get 'user/:name/:world', 
        :as => 'user', 
        :name => /.*/, 
        :to => 'users#show'
  # users
  scope :as => 'users', :controller => 'users', :path => 'users' do
    match '/:action(/page/:page)(/order/:order/:by)(/:world)(/race/:race)(/from/:starttime/till/:endtime)(/like/*name)', 
          :defaults => {
            :page   => 1
          },
          :via => [:get, :post]
    root action: 'index'
  end
 
  # adminpanel
  namespace :admin do 
    resources :achievements, :dumps, :members, :npcs, :news, :races, :worlds
    root :to => 'base#index'
  end
  
  match "*path", :to => "application#routing_error", :via => :all
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about   
  end
  
  def contact
    
  end
  
  def dumps
    @dumps = Dump.all
    @dumps = @dumps.shared unless current_member.try(:developer)
    
    if params[:path]
      @dumps = @dumps.where(:path => params[:path]).take
      
      @dumps_mapped = []
      files = @dumps.try(:files)
      
      files.sort.each do |file|
        dump_file = @dumps.dup
        dump_file.path = file
        @dumps_mapped << dump_file
      end if files
      
      @dumps = @dumps_mapped
    end
  end
  
  def index
    @news = News.order("created_at DESC")
    
    @news = @news.published unless current_member.try(:developer?)
  end
  
  def show
    @news = News.find(params[:id])
    
    raise ActiveRecord::RecordNotFound unless @news.try(:published?) || current_member.try(:developer?)
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
  def news_format(text)
    #simple_format(text, {class: %w{news content}}, {wrapper_tag: "p", sanitize: false})
    render inline: text
  end
  
  def news_action_bar(news, options = {})
    options[:glue] ||= " - "
    options[:wrap] ||= %w{[ ]}
    
    action_bar = {
      show: link_to('Show', news),
      edit: link_to('Edit', edit_admin_news_path(news)),
      destroy: link_to('Destroy', [:admin, news], 
                       method: :delete, data: { confirm: 'Are you sure?' })
    }
    options[:only] ||= action_bar.keys
    
    # we want to be able to wrap around text nodes and content tags
    action_bar.except(options[:except]).only(options[:only]).values
              .map { |a| options[:wrap][0] + a.html_safe + options[:wrap][1] }
              .join(options[:glue]).html_safe
    #safe_join([options[:wrap][0], 
    #           safe_join(action_bar, options[:wrap][1] + options[:glue] + options[:wrap][0]), 
    #           options[:wrap][1]])
  end
end

app/views/home/_actions.html.erb
<li><%= link_to t('home.index.human'), url_for({:controller => '/home', :action => 'index'}) %></li>

app/views/home/_e_record_not_found.html.erb
<%= t "home.show.record_not_found" %>

app/views/home/about.html.erb
<h1><%= t ".heading" %></h1>

<h2><%= t ".thanks.heading" %></h2>
<p><%= t ".thanks.text" %></p>

<h2><%= t ".impressum.heading" %></h2>
<p><%= t ".impressum.text" %></p>

<h2><%= t ".analytics.service" %></h2>
<p><%= t ".analytics.text" %></p>

<p>
  <%= t(".contact.text") %>
  <%= link_to t(".contact.link"), contact_url %>
</p>

app/views/home/contact.html.erb
<h1><%= t(".heading") %></h1>
<p><%= t ".text", :mail => contact_mail %></p>

app/views/home/dumps.html.erb
<h1><%= t(".heading") %></h1>

<table>
  <thead>
    <tr>
      <th><%= Dump.human_attribute_name(:name) %></th>
      <th><%= Dump.human_attribute_name(:path) %></th>
      <th><%= Dump.human_attribute_name(:files) %></th>
      <th><%= Dump.human_attribute_name(:updated_at) %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @dumps.each do |dump| %>
      <tr>
        <td><%= dump.name %></td>
        <td><%= link_to dump_path(dump), dump_path(dump) %></td>
        <td><%= dump.files.length %></td>
        <td><%= time_tag dump.updated_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to_back %>

app/views/home/index.html.erb
<% @title = "FWRails" %>
<h1><%= News.model_name.human %></h1>

<% @news.each do |news| %>
  <% news.max_content_summary_count = 40 %>
  <h2 class="news heading">
    <%= news.heading %>
    <%= news_action_bar(news) if current_member.try(:developer?) %>
  </h2>
  <p class="news publish_at">
    <em><%= News.human_attribute_name("publish_at") %></em>
    <%= time_tag news.publish_at.to_date %>
  </p>
  <div class="news content_summary simple_format long_text">
    <%= news_format(news.content_summary) %>
    <%= link_to t(".read_further"), news, id: "read_further" if news.content_summarized? %>
  </div>
  
<% end %>

app/views/home/show.html.erb
<% @title = "#{News.model_name.human}: #{@news.heading}" %>
<section id="news">
  <h1 class="news heading">
    <%= @title %>
    <%= news_action_bar(@news) if current_member.try(:developer?) %>
  </h1>
  <p class="news publish_at">
    <em><%= News.human_attribute_name("publish_at") %></em>
    <%= time_tag @news.publish_at.to_date %>
  </p>
  <p class="news updated_at">
    <em><%= News.human_attribute_name("updated_at") %></em>
    <%= time_tag @news.public_updated_at %>
  </p>
  <div class="news content simple_format long_text">
    <%= news_format(@news.content) %>
  </div>
</section>

<%= link_to t(".back"), root_url %>