config/routes.rb
Freewar3::Application.routes.draw do 
  devise_for :members,
             controllers: {
               sessions: "sessions"
             }
  # :param => /.*/ prevents failing on a name with a period
  root :to => 'home#index'
  
  # ukimgs      
  get 'ukimgs/tag/:id/:tag_id/(up|down|report)',
        :as => 'ukimgs_tag',
        :to => 'ukimgs#tag'
      
  get 'ukimgs(/sets/:sets)(/tags/:tags)',
        :as => 'ukimgs',
        :to => 'ukimgs#index'
  
  # about
  scope :controller => :home, :path => '/' do
    get '/about', :action => :about, :as => 'about'
    get '/contact', :action => :contact, :as => 'contact'
    get '/dumps(/:path)', :action => :dumps, :as => 'dumps'
    get '/impressum', :action => :impressum, :as => 'impressum'
  end
  
  # single achievement
  get 'achievement/:name(/:stage)', 
        :as => 'achievement',
        :to => 'achievements#show'
  # Achievements
  scope :as => 'achievements', :controller => :achievements, :path => '/achievements' do
    get '/group_progress/:group/:users.:format',
          :action => 'group_progress',
          :as     => 'group_progress'
          
    get '/rank(/show/:ids)(/page/:page)(/order/:order/:by)(/:world)',
          :action => 'rank',
          :as     => 'rank'
    get '/unachieved(/:world)', 
          :action => 'unachieved',
          :as     => 'unachieved'
    
    get '(/:world)', 
        :action => 'index',
        :as     => 'index'
    root action: 'index'
  end
  
  # Areas  
  scope :as => 'areas', :controller => 'areas', :path => '/areas' do
    get '/:name/places', 
          :action => 'places',
          :as => 'places'
    get '/:name', 
          :action => 'show',
          :as => 'show'
  end
  
  
  # single clan
  get 'clan/:id/:world', 
        :as => 'clan', 
        :to => 'clans#show'
  # clans
  scope :as => 'clans', :controller => 'clans', :path => '/clans' do
    match '/:action(/page/:page)(/order/:order/:by)(/:world)(/from/:starttime/till/:endtime)(/like/*name)', 
          :defaults => {
            :page   => 1
          },
          :via => [:get, :post]
    root action: 'index'
  end
  
  # single extension
  get '/extensions/show/:id', :to => 'extensions#show', :as => 'extension'
  
  # extensions
  scope :as => 'extensions', :controller => :extensions, :path => '/extensions' do 
    get '/:action'
    
    root :action => :index
  end
  
      
  # graphs
  scope :as => 'graphs', :controller => :graphs, :path => '/graphs' do
    root :action => 'index'
    
    match '/achievements(/:mode)', 
          :action => 'achievements', 
          :as => 'achievements',
          :via => [:get, :post] 
    match '/statistics',
          action: 'statistics',
          as: 'statistics',
          via: [:get, :post]
  end
  
  # map
  scope :as => 'map', :controller => :map, :path => '/map' do
    post '',
         :action => 'index'
    get '(/:x,:y)(/radius/:radius)',
        :action => 'index',
        :as => 'root'

    get '/show/:x,:y',
        :action => 'show',
        :as => 'place'
  end
  
  #news
  get '/news' => 'feeds#news', :as => 'news_feed',
      :defaults => {
        :format => 'atom'
      }
  get '/news/:id', :to => 'home#show', :as => 'news'
  
  # npcs
  get '/npcs/api(.:format)', :to => 'npcs#api', :as => 'npcs_api'
  resources :npcs, only: [:index, :show]
  
  get '/spotlights', as: "spotlights", to: "spotlights#show"
  
  # slmania
  scope as: 'slmania', controller: :slmania, path: '/slmania' do
    root action: 'index', as: 'index'
    
    scope path: '/:member', as: 'user' do 
      get '/npc/:name',  action: 'evaluate_npc', as: 'npc'
      get '/item/:name', action: 'evaluate_item', as: 'item'
      get '/soul_capsule', action: 'soul_capsule', as: 'soul_capsule'
      
      root action: 'list_actions'
    end
  end
  
  # single statistic/
  get 'statistic/:name(/:world)', 
        :as => 'statistic',
        :to => 'statistics#show'
  
  # statistics
  scope :as => 'statistics', :controller => :statistics, :path => '/statistics' do
    root action: 'index'
    
    get '/:action(/:world)'
  end
  
  # tools
  scope :as => 'tools', :controller => 'tools', :path => 'tools' do
    match '/railpatterns(/:active_pattern)', :as => 'railpatterns', 
                                          :action => 'railpatterns',
                                          :defaults => {
                                            :active_pattern => "Lebensschnitt"
                                          },
                                          :via => [:get, :post]
    match '/ability_calc', :as => 'ability_calc', :action => 'ability_calc', :via => [:get, :post]
  end
  
  # single user
  get 'user/:name/:world', 
        :as => 'user', 
        :name => /.*/, 
        :to => 'users#show'
  # users
  scope :as => 'users', :controller => 'users', :path => 'users' do
    match '/:action(/page/:page)(/order/:order/:by)(/:world)(/race/:race)(/from/:starttime/till/:endtime)(/like/*name)', 
          :defaults => {
            :page   => 1
          },
          :via => [:get, :post]
    root action: 'index'
  end
 
  # adminpanel
  namespace :admin do 
    resources :achievements, :dumps, :members, :npcs, :news, :races, :worlds
    root :to => 'base#index'
  end
  
  match "*path", :to => "application#routing_error", :via => :all
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  def index
    # max radius
    @max_radius = 15
    
    # strong params
    @params = map_params
    
    # tile width/height in px
    @tile_size = 50
    
    # get places and draw border
    @places = Place.invert(:houses)
                   .minimap(@params[:x], @params[:y], @params[:radius] + 1)
                   .includes(:npcs)
    @places_with_border = draw_border @places
    
    # npcs
    @npcs = Npc.in_range(@params[:x], @params[:y], @params[:radius]).order(name: :asc)
    
    # dimensions
    @map_dimensions = map_dimensions(@places_with_border)
    
    # world for path
    @image_world = World.image_world.take
  end

  def show
  end
  
  private
  
  def draw_border(places)
    # execute query
    places = places.to_a
    
    # get boundary
    dimensions = map_dimensions(places)
    
    # walk dimensions
    (dimensions[:min_x]..dimensions[:max_x]).each do |x|
      (dimensions[:min_y]..dimensions[:max_y]).each do |y|
        # no place at the coordinates
        if places.select { |place| place.pos_x == x && place.pos_y == y}.empty?
          # so draw border
          places << Place.border_place(x, y)
        end
      end
    end
    
    # return
    places
  end
  
  # calculates dimensions
  # min, max, width, height
  def map_dimensions(places)
    boundaries = {
      min_x: places.min_by { |p| p.pos_x }.pos_x,
      max_x: places.max_by { |p| p.pos_x }.pos_x,
      min_y: places.min_by { |p| p.pos_y }.pos_y,
      max_y: places.max_by { |p| p.pos_y }.pos_y
    }
    
    boundaries.merge({
      height: boundaries[:max_y] - boundaries[:min_y] + 1,
      width: boundaries[:max_x] - boundaries[:min_x] + 1
    })
  end
  
  # strong params
  def map_params
    # numeric only params
    [:x, :y, :radius].each do |key|
      params[key] = params[key].to_i
    end
    
    # defaults here since we allow them per get in routes match and post via form
    {x: 92, y: 105, radius: 2}.each do |param, default|
      params[param] = default if params[param] == 0
    end
    
    params[:radius] = [1, [@max_radius, params[:radius].abs].min].max
    
    params.permit(:x, :y, :radius)
  end
  
end

app/helpers/map_helper.rb
module MapHelper
  include NpcsHelper
end

app/views/map/index.html.erb
<h1><%= t ".heading" %></h1>

<%= link_to t(".link_to_this_page"), map_root_url(@params), class: "to_this_page" %>

<%= field_set_tag t(".control.heading") do %>
  <%= form_tag(map_root_url, method: :post, id: "map_control") do %>

  <%= label_tag :x, t(".control.label.x") %>
  <%= number_field_tag :x, @params[:x] %>

  <%= label_tag :y, t(".control.label.y") %>
  <%= number_field_tag :y, @params[:y] %>

  <%= label_tag :radius, t(".control.label.radius") %>
  <%= select_tag :radius, options_for_select(1..@max_radius, @params[:radius]) %>

  <%= submit_tag t(".control.submit") %>
  <% end %>
<% end %>

<div id="minimap" style="height: <%= (@map_dimensions[:height] + 2) * @tile_size %>px; 
                         width: <%= (@map_dimensions[:width] + 2) * @tile_size %>px;">
  <% (@map_dimensions[:min_x]..@map_dimensions[:max_x]).each do |grid_x| %>
    <%= content_tag(:div , id: "grid_x#{grid_x}", 
                           class: %w{place grid x},
                           style: "top: 0px; " +
                                  "left: #{(grid_x - @map_dimensions[:min_x] + 1) * @tile_size}px; ") do %>
    <%= number_with_delimiter(grid_x) %>
    <% end %>
  <% end %>
  
  <% (@map_dimensions[:min_y]..@map_dimensions[:max_y]).each do |grid_y| %>
    <%= content_tag(:div , id: "grid_y#{grid_y}", 
                           class: %w{place grid y},
                           style: "top: #{(grid_y - @map_dimensions[:min_y] + 1) * @tile_size}px; " +
                                  "left: 0px; ") do %>
    <%= number_with_delimiter(grid_y) %>
    <% end %>
  <% end %>
  
  <% @places_with_border.each do |place| %>
    <% top = (place.pos_y - @map_dimensions[:min_y] + 1) * @tile_size %>
    <% left = (place.pos_x - @map_dimensions[:min_x] + 1) * @tile_size %>
    <%= link_to(map_root_url(x: place.pos_x, y: place.pos_y, radius: @params[:radius]) , 
                id: "place#{place.pos_key}", 
                class: ["place"] << ("out_of_bounds" if place.los_distance(@params[:x], @params[:y]) > @params[:radius]),
                style: "top: #{top}px; " +
                       "left: #{left}px; " +
                       "background: url(#{place.gfx_path(@image_world)});",
                title: position_text(place)) do %>
      <%= image_tag capsule_map_path(place.npcs.size, @image_world),
                    alt: "#{place.npcs.size}_npcs",
                    class: "soul_capsule" %>
    <% end %>
  <% end %>
</div>

<h2><%= t ".npcs.heading" %></h2>
<table id="npcs">
  <caption><%= t ".npcs.table.caption", count: @npcs.length %></caption>
  <thead>
    <tr>
      <th>
        <%= label_tag :toggle_all_npcs, t(".npcs.table.head.show") %>
        <%= check_box_tag :toggle_all_npcs %>
      </th>
      <th><%= Npc.human_attribute_name(:name) %></th>
      <th><%= t ".npcs.table.head.position" %></th>
      <th><%= Npc.human_attribute_name(:gold) %></th>
    </tr>
  </thead>
  <tbody>
    <% @npcs.each do |npc| %>
    <tr>
      <td><%= check_box_tag npc, npc.id, false, class: "toggle_npc" %></td>
      <td><%= label_tag npc, npc.name %></td>
      <td><%= position_text(npc) %></td>
      <td><%= number_with_delimiter(npc.gold) %></td>
    </tr>
    <% end %>
  </tbody>
  
</table>

<script type="text/javascript">
  var places = <%= @places.to_json(includes: :npcs).html_safe %>,
      npcs = <%= @npcs.to_json.html_safe %>;
</script>

app/views/map/show.html.erb
<h1>Map#show</h1>
<p>Find me in app/views/map/show.html.erb</p>